sudo: required
dist: trusty
language: python
python:
  - 3.5
install:
  - pip install -q tox
  - pip install -q coveralls
before_script:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -qq
  - sudo apt-get install ffmpeg -y
env:
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=coverage
script:
  - tox -e $TOXENV
after_success:
  - test $TOXENV = "coverage" && coveralls
