sudo: required
dist: trusty
language: python
python:
- 3.5
cache:
  directories:
  - $TRAVIS_BUILD_DIR/ffmpeg
install:
- pip install -q tox
- pip install -q coveralls
- pip install -q sphinx>=1.3 sphinx_rtd_theme
before_script:
# Install ffmpeg
- mkdir -p ffmpeg
- test -x ffmpeg/ffprobe || (wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz && tar xf ffmpeg-release-64bit-static.tar.xz --strip-components 1 -C ffmpeg)
- export PATH=$TRAVIS_BUILD_DIR/ffmpeg:$PATH
# Install system dependencies for py3exiv2
- sudo apt-get install libexiv2-dev -y
- sudo apt-get install libboost-python-dev -y
- ffprobe -formats
- ffprobe -codecs
- ffprobe -pix_fmts
env:
- TOXENV=py34
- TOXENV=py35
script:
- pip install .[exiv2]
- tox -e $TOXENV
- py.test --doctest-modules madam
- sphinx-build -b html doc/ doc/_build/html
after_success:
- test $TOXENV = "py35" && coveralls
before_deploy:
- pip install wheel
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: eseifert
  password:
    secure: q7r+zIDG+m7qrXFC/Cn2TaPXhSU9cnE+1m8j6smMlKfuNYcp1K56RYOzTn7TQgURLGaVhsw1ZpcB4ib1kt7uVvBMZD+gaMsZ3rSfF0wA+OjY/aUUHc3SP/n8JHexdTmrQJVVrX1yegoHRtl5JtApKbPRx6TTBdoPzJY70+R94PcIdM0Y1+MlHrAmvOsHUrBPt6uC/bfbE70/RkNStNBVFX3NpExi3+0VFqDtNpBkXBRs1Yot1l/pQCyKgHkm3mJMmBk8kv4mASOJSIOokv3IQb7vDx+G1jTyf7NCadkZLn9OJtBcd5CSL4kDBo3p61zprZptg4XW0zFbqWr2FKTEqGWEN/CSgF4GmCS25iTfkMLKjrYp4vD8hIHhW2q/GM/0fs8yuepljUeXgRiIYBI5DCx1I9TG2Yd8oENDUe3uJvSCaSsWr1QeB0NMlpZUo0fKsjhTzCFdTUnbsUhpyQVEVXa4nEz12ogXLllH5atvCV/kYoUHKGj36GCIsY98oD4DycKany3VQDGJGrv/TsfSrCMny1MVysPRvosdyOCACPUyawqTqJawKZS/DVRePfHaSnpY4X111BOf7vJkQVUOM4Xpsw0hirRTdrG7m0OGYxVzQUXl8z7FcDRVDiPpPJJKkZM/kWKeFOHG3MJGA4S8bFSMiIBRK6vGdGKq0/coiRs=
  on:
    tags: true
    distributions: bdist_wheel
    repo: eseifert/madam
    condition: $TOXENV = "py35"
