sudo: required
dist: trusty
before_script:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - sudo apt-get install ffmpeg -y
language: python
python:
  - 3.5
install:
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=madam setup.py test --addopts tests
after_success:
  coveralls
