sudo: required
dist: trusty
before_script:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -qq
  - sudo apt-get install ffmpeg -y
language: python
python:
  - 3.5
install:
  - pip install -q tox
  - pip install -q coveralls
script:
  - tox -e $TOXENV
env:
  - TOXENV=py34
  - TOXENV=py35
after_success:
  - test $TOXENV = "py35"
    && coveralls
