sudo: required
dist: trusty
before_script:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - sudo apt-get dist-upgrade -q -y
  - sudo apt-get install ffmpeg -y
language: python
python:
  - 3.5
# command to run tests
script: python setup.py test --addopts tests
