sudo: required
dist: trusty
cache: /var/cache/apt/archives
before_script:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -qq
  - sudo apt-get install ffmpeg -y
language: python
python:
  - 3.5
install:
  - pip install -q tox
  - pip install -q coveralls
script:
  - tox
env:
  - TOXENV=py35
  - TOXENV=coverage
after_success:
  coveralls
